### ISSUE TITLE
Extension character limits are too restrictive

### ISSUE THREAD

**Issue by disaacs** [Shopify/asset_cloud#9]
/cc @chrisdonaldson @berkcaputcu related to https://github.com/Shopify/shopify/issues/40038

When accessing an asset file, the filename is validated using the following regex:
```
VALID_PATHS = /\A[a-z0-9][a-z0-9_\-\/]+([a-z0-9][\w\-\ \.\@]*\.\w{2,6})?\z/i
```
https://github.com/Shopify/asset_cloud/blob/e63c3f5f7a27a9063c01d761c30a72f0060d9948/lib/asset_cloud/base.rb#L12

Among other things, this does not allow single character extensions. I cannot think of a reason why this restriction exists (I've traced the restriction as far back as January 2008, when the code was imported from another repository). 

As this has caused a problem with some requested document uploads, I like to change this to allow 1 character extensions, or even no extension at all.

**Comment by chrisdonaldson** [comment]
We were using it for mime-type detection.

It is also doing it on documents uploaded through the admin and is silently failing as @andrewdunbar confirmed.

**Comment by berkcaputcu** [comment]
@jamesmacaulay @bouk can you review this?

**Comment by bouk** [comment]
I don't see a problem with being less restrictive
